# Set the build language to Python
language: python

python: 3.6

# Install the codecov pip dependency
install:
  - pip install pipenv
  - pipenv install --dev --skip-lock

# Run the unit test
script:
  - pytest --pycodestyle
  - pytest --cov=./ --cov-config=.coveragerc

# Push the results back to codecov
after_success:
  - codecov
