[tool.poetry]
name = "stwfsapy"
version = "0.6.1"
description = "A library for match labels of thesaurus concepts to text and assigning scores to found occurrences."
authors = ["AutoSE <autose@zbw.eu>"]
license = "Apache-2.0"
readme = "README.md"
classifiers = [
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
homepage = "https://github.com/zbw/stwfsapy"

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
scipy = "~1.15"
scikit-learn = ">0.24,<2.0"
rdflib = "~7.1"


[tool.poetry.group.dev.dependencies]
pytest = "~8.4"
pytest-mock = "~3.14"


[tool.poetry.group.ci.dependencies]
pytest-cov = "~6.2"
ruff = "~0.12"
safety = "3.5.2"
bandit = "~1.8"

[tool.ruff]
target-version = "py310"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.bandit]
skips = ["B403", "B301"]
exclude_dirs = ["stwfsapy/tests"]
